### ISSUE TITLE
[1.18.1] Incompatible with CraftingTweaker - Loot Chests empty

### ISSUE THREAD

**Issue by pewblaze** [LimonBlaze/LootExtra#1]
Hi, so i am using your mod and i really love it! 
But the Loot Chests are empty when CraftingTweaker is installed (https://www.curseforge.com/minecraft/mc-mods/crafttweaker)
Without your mod its working fine. 
Not sure though if its your mod or CraftingTweak.

The newest Versions:
CraftTweaker-fabric-1.18.1-9.0.0+26
LootExtra-1.18-0.1.1
[latest.log](https://github.com/LimonBlaze/LootExtra/files/7994404/latest.log)

I opened the Issue also there: 
https://github.com/CraftTweaker/CraftTweaker/issues/1442

**Comment by jaredlll08** [comment]
You mixin is basically overwriting the whole method since you target the head and cancel it.

You most likely want to be using ModifyVariable instead which is more compatible with multiple mixins targeting the same thing.

Also just for reference, these are our mixins into LootTable.
https://github.com/CraftTweaker/CraftTweaker/blob/64862089df5976ffe340767827ec57408bd69b44/Fabric/src/main/java/com/blamejared/crafttweaker/mixin/common/transform/loot/MixinLootTable.java#L22

**Comment by LimonBlaze** [comment]
> You mixin is basically overwriting the whole method since you target the head and cancel it.
> 
> You most likely want to be using ModifyVariable instead which is more compatible with multiple mixins targeting the same thing.
> 
> Also just for reference, these are our mixins into LootTable. https://github.com/CraftTweaker/CraftTweaker/blob/64862089df5976ffe340767827ec57408bd69b44/Fabric/src/main/java/com/blamejared/crafttweaker/mixin/common/transform/loot/MixinLootTable.java#L22

Thanks for the information! It's true that I messed up the whole process, but after I read your mixins, I found it no easy to simply do a mixin just like yours to make the work done: no matter it's me wrapping your consumer or you wrapping mine, the type cast part can't be done properly. I wonder if there's any other solution that could be done only on my side to fix this without losing any functionality except Redirect the call to the raw generate method. It should work fine between my mod and yours, while leaving no space for a third mod to do its work (still better than the original work though). I will have to try the redirect solution first until another issue of incompatibility reported.
